---
# Configure profile

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ profile_services_enable }}"
  when: profile_enable_service
